[project]
name = "smart-home"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.uv.workspace]
members = ["apps/smart-home-ai-agent", "docs/spec-site"]
